// lib/services/app_localizations.dart

import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // App
      'app_title': 'AgriCare',
      'app_tagline': 'Your Partner in Modern Farming',
      'welcome': 'Welcome to AgriCare',
      'hello': 'Hello',
      'local_weather': 'Local Weather Forecast',
      'local_farm_area': 'Local Farm Area, India',
      'scattered_clouds': 'SCATTERED CLOUDS',
      'refresh_data': 'Refresh Data',
      'get_recommendations': 'Get Recommendations',
      'ai_crop_desc': 'Get AI-powered recommendations for the most profitable crops for your land.',
      'land_conditions_placeholder': 'Describe your land conditions here... e.g., Black soil in Maharashtra, good water availability from borewell, hot climate.',
      
      // Feedback
      'feedback': 'Feedback',
      'send_feedback': 'Send Feedback',
      'feedback_title': 'We Value Your Feedback',
      'feedback_desc': 'Help us improve AgriCare by sharing your thoughts, suggestions, or reporting issues.',
      'feedback_name': 'Your Name',
      'feedback_email': 'Your Email',
      'feedback_type': 'Feedback Type',
      'feedback_message': 'Your Message',
      'feedback_type_suggestion': 'Suggestion',
      'feedback_type_bug': 'Bug Report',
      'feedback_type_compliment': 'Compliment',
      'feedback_type_complaint': 'Complaint',
      'feedback_type_other': 'Other',
      'feedback_placeholder': 'Share your feedback here...',
      'feedback_success': 'Thank you for your feedback!',
      'feedback_error': 'Failed to send feedback. Please try again.',
      
      // Why AgriCare section
      'why_agricare_title': 'Why AgriCare',
      'why_agricare_body': 'AgriCare connects farmers with trusted, technology-enabled agricultural services. From on-demand tractor hire to soil testing and crop advisory, we help you make better decisions and get more from every acre.',
      'why_agricare_points': 'Why farmers choose us:\n• Verified service partners\n• Transparent pricing\n• Local language support\n• End-to-end booking and tracking',
      'read_more': 'Read More',
      
      // Local weather card
      'local_weather_card_title': 'Local Weather',
      'local_weather_card_body': 'See today\'s temperature, humidity and wind for your farm area.',
      'open': 'Open',
      
      // Auth
      'login': 'Login',
      'register': 'Register',
      'email': 'Email Address',
      'password': 'Password',
      'name': 'Full Name',
      'logout': 'Logout',
      'login_success': 'Login successful!',
      'register_success': 'Registration successful!',
      'logout_success': 'Logged out successfully',
      'farmer': 'Farmer',
      'vendor': 'Vendor',
      'select_user_type': 'Select User Type',
      
      // Navigation
      'home': 'Home',
      'profile': 'Profile',
      'my_bookings': 'My Bookings',
      'weather': 'Weather Forecast',
      'chat': 'Support Chat',
      'about_us': 'About Us',
      'contact': 'Contact',
      'be_partner': 'Being Partner',
      
      // Services
      'our_services': 'Our Services',
      'services_subtitle': 'Comprehensive agricultural solutions for modern farming',
      'soil_water_testing': 'Soil & Water Testing',
      'ploughing_services': 'Ploughing Services',
      'cultivation_services': 'Cultivation Services',
      'fertilizer_pesticides': 'Fertilizer & Pesticides',
      'borewell_services': 'Borewell Services',
      'irrigation_services': 'Irrigation Services',
      'transport_services': 'Transport Services',
      'contract_farming': 'Contract',
      
      // Service descriptions
      'soil_water_desc': 'Ensure healthy soil and water',
      'ploughing_desc': 'Field preparation made easy',
      'cultivation_desc': 'Complete crop cultivation',
      'fertilizer_desc': 'Boost growth safely',
      'borewell_desc': 'Boost growth safely',
      'irrigation_desc': 'Professional painting services',
      'transport_desc': 'Professional painting services',
      'contract_desc': 'Contract',
      
      // Booking
      'book_now': 'Book Now',
      'booking_for': 'Booking for',
      'confirm_booking': 'Confirm Booking',
      'phone_number': 'Phone Number',
      'address': 'Address / Location',
      'service_date': 'Preferred Service Date',
      'select_date': 'Select Date',
      'booking_success': 'Booking successful!',
      'payment_method': 'Payment Method',
      'pay_now': 'Pay Now',
      'upi_payment': 'UPI Payment',
      'upi_id': 'UPI ID',
      'scan_qr': 'Scan QR Code',
      'payment_instructions': 'Scan the QR code or use the UPI ID to make payment',
      'booking_error': 'Failed to book service',
      'fill_all_details': 'Please fill all the booking details',
      'invalid_phone': 'Please enter a valid 10-digit phone number',
      
      // Weather
      'weather_forecast': 'Weather Forecast',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'wind_speed': 'Wind Speed',
      'rainfall': 'Rainfall',
      
      // AI Crop Manager
      'ai_crop_manager': 'AI Crop Manager',
      'ask_question': 'Ask a question about crops...',
      'get_advice': 'Get AI Advice',
      
      // Footer
      'about_us_desc': 'AgriCare provides professional and trusted agricultural services delivered to your doorstep with just a few taps.',
      'quick_links': 'Quick Links',
      'contact_us': 'Contact Us',
      'location': 'Mahalingapur, Karnataka',
      'all_rights_reserved': 'All Rights Reserved',
      
      // Common
      'close': 'Close',
      'close_form': 'Close Form',
      'cancel': 'Cancel',
      'save': 'Save',
      'submit': 'Submit',
      'search': 'Search',
      'language': 'Language',
      'total': 'Total',
      'pending': 'Pending',
      'completed': 'Completed',
      'price': 'Price',
      'status': 'Status',
      'no_bookings': 'No bookings yet',
      'book_service': 'Book a service to get started!',
      'view_details': 'View Details',
      
      // Subservices - Soil & Water Testing
      'basic_soil_test': 'Basic Soil Health Test',
      'npk_analysis': 'Comprehensive NPK Analysis',
      'water_salinity': 'Water Salinity & pH Test',
      'heavy_metal': 'Heavy Metal Contamination Test',
      'micronutrient': 'Micronutrient Analysis',
      
      // Subservices - Ploughing
      'tractor_ploughing': 'Tractor Ploughing (per acre)',
      'deep_ploughing': 'Deep Ploughing',
      'bullock_service': 'Bullock Service',
      'rotavator': 'Rotavator Service',
      'harrow': 'Harrow Service',
      'land_leveling': 'Land Leveling',
      
      // Subservices - Cultivation
      'seed_sowing': 'Seed Sowing Services',
      'transplanting': 'Transplanting Services',
      'weeding': 'Weeding & Intercultivation',
      'mulching': 'Mulching Services',
      'harvesting': 'Crop Harvesting',
      
      // Subservices - Fertilizer
      'organic_fertilizer': 'Organic Fertilizer Supply',
      'npk_application': 'NPK Fertilizer Application',
      'pesticide_spray': 'Pesticide Spraying',
      'bio_pesticide': 'Bio-Pesticide Solutions',
      'foliar_nutrition': 'Foliar Nutrition Spray',
      
      // Subservices - Borewell
      'borewell_drilling': 'Borewell Drilling (up to 200 ft)',
      'pump_installation': 'Submersible Pump Installation',
      'borewell_cleaning': 'Borewell Cleaning & Maintenance',
      'water_testing': 'Water Yield Testing',
      'motor_repair': 'Motor Repair Services',
      
      // Subservices - Irrigation
      'drip_irrigation': 'Drip Irrigation Installation',
      'sprinkler_system': 'Sprinkler System Setup',
      'flood_irrigation': 'Flood Irrigation Management',
      'irrigation_repair': 'Irrigation System Repair',
      'pipeline': 'Water Pipeline Installation',
      
      // Subservices - Transport
      'farm_transport': 'Farm Produce Transport',
      'livestock_transport': 'Livestock Transportation',
      'equipment_transport': 'Farm Equipment Transport',
      'fertilizer_delivery': 'Fertilizer & Seed Delivery',
      'cold_storage': 'Cold Storage Transport',
      
      // Subservices - Contract
      'full_season': 'Full Season Crop Management',
      'crop_contract': 'Crop Cultivation Contract',
      'buyback': 'Buy-back Guarantee',
      'land_lease': 'Land Lease Contract',
      'custom_farming': 'Custom Farming Services',
      
      // Additional translations for pages
      'customer_reviews': 'Customer Reviews',
      'real_feedback': 'Real feedback from verified customers',
      'verified': 'Verified',
      'helpful': 'Helpful',
      'yes': 'Yes',
      'no': 'No',
      'view_all_reviews': 'View All Reviews',
      'all_customer_reviews': 'All Customer Reviews',
      'reviews_average': 'reviews • {rating} ⭐ average',
      'no_reviews_yet': 'No reviews yet',
      'be_first_review': 'Be the first to leave a review!',
      'leave_review': 'Leave a Review',
      
      // Sample feedback data
      'sample_user_1': 'Ramesh Kumar',
      'sample_user_2': 'Sunita Devi',
      'sample_service_1': 'Tractor Ploughing Service',
      'sample_service_2': 'NPK Soil Testing',
      'sample_comment_1': 'Excellent service! The tractor operator was very professional and completed the work on time. My field was perfectly ploughed. Highly recommend!',
      'sample_comment_2': 'Good service and detailed soil report. The testing helped me understand my soil better. Only suggestion is to provide organic fertilizer recommendations.',
      'sample_date_1': '2 days ago',
      'sample_date_2': '1 week ago',
      
      // Feedback service names
      'feedback_service_suggestion': 'Suggestion',
      'feedback_service_bug': 'App Experience',
      'feedback_service_compliment': 'Service Appreciation',
      'feedback_service_complaint': 'Service Issue',
      'feedback_service_other': 'Other Feedback',
      'feedback_service_general': 'General Service',
      'about_agricare': 'About AgriCare',
      'empowering_farmers': 'Empowering Farmers with Technology',
      'our_story': 'Our Story',
      'story_text': 'AgriCare was founded with a simple mission: to make agricultural services accessible to every farmer in rural India. We bridge the gap between farmers and skilled service providers using technology.',
      'farmers': 'Farmers',
      'service_providers': 'Service Providers',
      'services_completed': 'Services Completed',
      'our_mission': 'Our Mission',
      'mission_text': 'To empower farmers with easy access to quality agricultural services at affordable prices.',
      'our_vision': 'Our Vision',
      'vision_text': 'To become the most trusted platform for agricultural services in India.',
      'our_values': 'Our Values',
      'trust': 'Trust',
      'trust_desc': 'Building lasting relationships with farmers',
      'quality': 'Quality',
      'quality_desc': 'Ensuring the best service standards',
      'innovation': 'Innovation',
      'innovation_desc': 'Using technology to solve problems',
      'community': 'Community',
      'community_desc': 'Supporting rural development',
      'contact_us': 'Contact Us',
      'were_here_to_help': 'We\'re here to help you',
      'phone': 'Phone',
      'whatsapp': 'WhatsApp',
      'address': 'Address',
      'send_us_message': 'Send us a Message',
      'your_name': 'Your Name',
      'your_email': 'Your Email',
      'your_phone': 'Your Phone',
      'your_message': 'Your Message',
      'send_message': 'Send Message',
      'office_locations': 'Office Locations',
      'head_office': 'Head Office',
      'regional_office': 'Regional Office',
      'follow_us': 'Follow Us',
      'we_value_feedback': 'We value your feedback and suggestions',
      'send_us_feedback': 'Send us your feedback',
      'rate_experience': 'Rate your experience',
      'feedback_type': 'Feedback Type',
      'general_feedback': 'General Feedback',
      'bug_report': 'Bug Report',
      'feature_request': 'Feature Request',
      'complaint': 'Complaint',
      'compliment': 'Compliment',
      'your_feedback': 'Your Feedback',
      'tell_us_think': 'Tell us what you think...',
      'submit_feedback': 'Submit Feedback',
      'thank_you_feedback': 'Thank you for your feedback!',
      'quick_feedback': 'Quick Feedback',
      'excellent_service': 'Excellent Service!',
      'easy_to_use': 'Easy to Use',
      'need_improvements': 'Need Improvements',
      'great_support': 'Great Support',
      'more_features': 'More Features',
      'be_partner': 'Being Partner',
      'join_network': 'Join our network of agricultural service providers',
      'partner_benefits': 'Partner Benefits',
      'more_customers': 'More Customers',
      'flexible_work': 'Flexible Work',
      'fair_payments': 'Fair Payments',
      'training_support': 'Training Support',
      'insurance_coverage': 'Insurance Coverage',
      'how_it_works': 'How It Works',
      'apply_online': 'Apply Online',
      'fill_application': 'Fill out our simple application form',
      'verification': 'Verification',
      'verify_skills': 'We verify your skills and documents',
      'training': 'Training',
      'free_training': 'Free training on our platform',
      'start_earning': 'Start Earning',
      'receive_requests': 'Begin receiving service requests',
      'requirements': 'Requirements',
      'experience_required': 'Experience in agricultural services',
      'valid_id': 'Valid ID proof and address proof',
      'smartphone_knowledge': 'Basic smartphone knowledge',
      'bank_account': 'Bank account for payments',
      'serve_rural': 'Willingness to serve rural areas',
      'ready_to_join': 'Ready to Join?',
      'start_earning_today': 'Start earning with AgriCare today',
      'apply_now': 'Apply Now',
      'settings': 'Settings',
      'account': 'Account',
      'edit_profile': 'Edit Profile',
      'alerts': 'Alerts',
      'profile_information': 'Profile Information',
      'update_personal_details': 'Update your personal details',
      'privacy_security': 'Privacy & Security',
      'manage_privacy_settings': 'Manage your privacy settings',
      'payment_methods': 'Payment Methods',
      'manage_payment_options': 'Manage your payment options',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'receive_app_notifications': 'Receive app notifications',
      'email_notifications': 'Email Notifications',
      'receive_updates_email': 'Receive updates via email',
      'sms_notifications': 'SMS Notifications',
      'receive_sms_updates': 'Receive SMS updates',
      'push_notifications': 'Push Notifications',
      'receive_push_notifications': 'Receive push notifications',
      'app_preferences': 'App Preferences',
      'dark_mode': 'Dark Mode',
      'use_dark_theme': 'Use dark theme',
      'currency': 'Currency',
      'support_about': 'Support & About',
      'help_faq': 'Help & FAQ',
      'get_help_answers': 'Get help and find answers',
      'send_feedback': 'Send Feedback',
      'share_thoughts': 'Share your thoughts with us',
      'about_agricare': 'About AgriCare',
      'version': 'Version 2.0.1',
      'account_actions': 'Account Actions',
      'sign_out': 'Sign Out',
      'sign_out_account': 'Sign out of your account',
      'delete_account': 'Delete Account',
      'permanently_delete': 'Permanently delete your account',
      'coming_soon': 'Coming Soon',
      'feature_development': 'This feature is under development and will be available soon.',
      'ok': 'OK',
      'confirm_sign_out': 'Confirm Sign Out',
      'sure_sign_out': 'Are you sure you want to sign out?',
      'cancel': 'Cancel',
      'confirm_delete': 'Confirm Account Deletion',
      'sure_delete_account': 'Are you sure you want to permanently delete your account? This action cannot be undone.',
      'delete': 'Delete',
      'select_language': 'Select Language',
      'english': 'English',
      'kannada': 'ಕನ್ನಡ (Kannada)',
      'hindi': 'हिंदी (Hindi)',
      'select_currency': 'Select Currency',
      
      // Booking Form - Bill Calculator
      'area_acres': 'Area (Acres)',
      'enter_area_acres': 'Enter area in acres',
      'area_required': 'Area is required',
      'valid_area': 'Please enter a valid area',
      'bill_calculator': 'Bill Calculator',
      'rate_per_acre': 'Rate per acre:',
      'enter_area_calculate': 'Enter area to calculate total amount',
      'total_amount': 'Total Amount:',
      'number_of_persons': 'Number of Persons',
      'enter_number_persons': 'Enter number of persons',
      'persons_required': 'Number of persons is required',
      'valid_persons': 'Please enter a valid number of persons',
      'number_of_days': 'Number of Days',
      'enter_number_days': 'Enter number of days',
      'days_required': 'Number of days is required',
      'valid_days': 'Please enter a valid number of days',
      'rate_per_person_day': 'Rate per person per day:',
      'persons_days': 'Persons × Days:',
      'enter_persons_days_calculate': 'Enter persons and days to calculate total amount',
      'select_fertilizer_product': 'Select Fertilizer Product',
      'choose_fertilizer': 'Choose fertilizer product',
      'select_pesticide_product': 'Select Pesticide Product',
      'choose_pesticide': 'Choose pesticide product',
      'per_unit': 'per unit',
      'quantity_bags_packs': 'Quantity (Bags/Packs)',
      'quantity_bottles_packs': 'Quantity (Bottles/Packs)',
      'enter_bags_packs': 'Enter number of bags/packs',
      'enter_bottles_packs': 'Enter number of bottles/packs',
      'quantity_required': 'Quantity is required',
      'valid_quantity': 'Please enter a valid quantity',
      'fertilizer_bill_calculator': 'Fertilizer Bill Calculator',
      'pesticide_bill_calculator': 'Pesticide Bill Calculator',
      'selected_product': 'Selected Product:',
      'price_per_unit': 'Price per unit:',
      'quantity_price': 'Quantity × Price:',
      'select_product_quantity': 'Select product and enter quantity to calculate total amount',
      'distance_kilometers': 'Distance (Kilometers)',
      'enter_distance_km': 'Enter distance in kilometers',
      'distance_required': 'Distance is required',
      'valid_distance': 'Please enter a valid distance',
      'transport_bill_calculator': 'Transport Bill Calculator',
      'rate_per_kilometer': 'Rate per kilometer:',
      'distance_rate': 'Distance × Rate:',
      'enter_distance_calculate': 'Enter distance to calculate transport cost',
    },
    
    'kn': {
      // App
      'app_title': 'ಅಗ್ರಿಕೇರ್',
      'app_tagline': 'ಆಧುನಿಕ ಕೃಷಿಯಲ್ಲಿ ನಿಮ್ಮ ಪಾಲುದಾರ',
      'welcome': 'ಅಗ್ರಿಕೇರ್ ಗೆ ಸ್ವಾಗತ',
      'hello': 'ನಮಸ್ಕಾರ',
      'local_weather': 'ಸ್ಥಳೀಯ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
      'local_farm_area': 'ಸ್ಥಳೀಯ ಕೃಷಿ ಪ್ರದೇಶ, ಭಾರತ',
      'scattered_clouds': 'ಚದುರಿದ ಮೋಡಗಳು',
      'refresh_data': 'ಡೇಟಾವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ',
      'get_recommendations': 'ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
      'ai_crop_desc': 'ನಿಮ್ಮ ಭೂಮಿಗೆ ಹೆಚ್ಚು ಲಾಭದಾಯಕ ಬೆಳೆಗಳಿಗೆ AI-ಚಾಲಿತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      'land_conditions_placeholder': 'ನಿಮ್ಮ ಭೂಮಿಯ ಪರಿಸ್ಥಿತಿಗಳನ್ನು ಇಲ್ಲಿ ವಿವರಿಸಿ... ಉದಾ., ಮಹಾರಾಷ್ಟ್ರದಲ್ಲಿ ಕಪ್ಪು ಮಣ್ಣು, ಬೋರ್‌ವೆಲ್‌ನಿಂದ ಉತ್ತಮ ನೀರಿನ ಲಭ್ಯತೆ, ಬಿಸಿ ವಾತಾವರಣ.',
      
      // Feedback
      'feedback': 'ಪ್ರತಿಕ್ರಿಯೆ',
      'send_feedback': 'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ',
      'feedback_title': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ನಾವು ಗೌರವಿಸುತ್ತೇವೆ',
      'feedback_desc': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳು, ಸಲಹೆಗಳು ಅಥವಾ ಸಮಸ್ಯೆಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳುವ ಮೂಲಕ ಅಗ್ರಿಕೇರ್ ಅನ್ನು ಸುಧಾರಿಸಲು ಸಹಾಯ ಮಾಡಿ.',
      'feedback_name': 'ನಿಮ್ಮ ಹೆಸರು',
      'feedback_email': 'ನಿಮ್ಮ ಇಮೇಲ್',
      'feedback_type': 'ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರಕಾರ',
      'feedback_message': 'ನಿಮ್ಮ ಸಂದೇಶ',
      'feedback_type_suggestion': 'ಸಲಹೆ',
      'feedback_type_bug': 'ದೋಷ ವರದಿ',
      'feedback_type_compliment': 'ಪ್ರಶಂಸೆ',
      'feedback_type_complaint': 'ದೂರು',
      'feedback_type_other': 'ಇತರೆ',
      'feedback_placeholder': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಇಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ...',
      'feedback_success': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!',
      'feedback_error': 'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
      
      // Why AgriCare section
      'why_agricare_title': 'ಏಕೆ ಅಗ್ರಿಕೇರ್',
      'why_agricare_body': 'ಅಗ್ರಿಕೇರ್ ವಿಶ್ವಾಸಾರ್ಹ, ತಂತ್ರಜ್ಞಾನ ಸಹಿತ ಕೃಷಿ ಸೇವೆಗಳ ಮೂಲಕ ರೈತರನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ. ಟ್ರಾಕ್ಟರ್ ಬಾಡಿಗೆದಿಂದ ಮಣ್ಣು ಪರೀಕ್ಷೆ ಮತ್ತು ಬೆಳೆ ಸಲಹೆವರೆಗೆ, ಪ್ರತಿಯೊಂದು ಎಕರೆಗಿಂತ ಹೆಚ್ಚು ಫಲಿತಾಂಶ ಪಡೆಯಲು ನಾವು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.',
      'why_agricare_points': 'ರೈತರು ನಮ್ಮನ್ನು ಆಯ್ಕೆಮಾಡುವ ಕಾರಣಗಳು:\n• ಪರಿಶೀಲಿತ ಸೇವಾ ಪಾಲುದಾರರು\n• ಪಾರದರ್ಶಕ ಬೆಲೆ ನಿಗದಿ\n• ಸ್ಥಳೀಯ ಭಾಷಾ ಬೆಂಬಲ\n• ಒಟ್ಟಾರೆ ಬುಕ್ಕಿಂಗ್ ಮತ್ತು ಟ್ರ್ಯಾಕಿಂಗ್',
      'read_more': 'ಇನ್ನಷ್ಟು ಓದಿ',
      
      // Local weather card
      'local_weather_card_title': 'ಸ್ಥಳೀಯ ಹವಾಮಾನ',
      'local_weather_card_body': 'ಇಂದು ನಿಮ್ಮ ಕೃಷಿ ಪ್ರದೇಶದ ತಾಪಮಾನ, ಆರ್ದ್ರತೆ ಮತ್ತು ಗಾಳಿಯ ವೇಗವನ್ನು ನೋಡಿ.',
      'open': 'ತೆರೆ',
      
      // Auth
      'login': 'ಲಾಗಿನ್',
      'register': 'ನೋಂದಣಿ',
      'email': 'ಇಮೇಲ್ ವಿಳಾಸ',
      'password': 'ಪಾಸ್ವರ್ಡ್',
      'name': 'ಪೂರ್ಣ ಹೆಸರು',
      'logout': 'ಲಾಗೌಟ್',
      'login_success': 'ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      'register_success': 'ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      'logout_success': 'ಯಶಸ್ವಿಯಾಗಿ ಲಾಗೌಟ್ ಆಗಿದೆ',
      'farmer': 'ರೈತ',
      'vendor': 'ಮಾರಾಟಗಾರ',
      'select_user_type': 'ಬಳಕೆದಾರ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      
      // Navigation
      'home': 'ಮುಖಪುಟ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'my_bookings': 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು',
      'weather': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
      'chat': 'ಸಹಾಯ ಚಾಟ್',
      'about_us': 'ನಮ್ಮ ಬಗ್ಗೆ',
      'contact': 'ಸಂಪರ್ಕಿಸಿ',
      'be_partner': 'ಭಾಗಿಯಾಗಿರಿ',
      
      // Services
      'our_services': 'ನಮ್ಮ ಸೇವೆಗಳು',
      'services_subtitle': 'ಆಧುನಿక ಕೃಷಿಗಾಗಿ ಸಮಗ್ರ ಕೃಷಿ ಪರಿಹಾರಗಳು',
      'soil_water_testing': 'ಮಣ್ಣು ಮತ್ತು ನೀರಿನ ಪರೀಕ್ಷೆ',
      'ploughing_services': 'ಉಳುಮೆ ಸೇವೆಗಳು',
      'cultivation_services': 'ಕೃಷಿ ಸೇವೆಗಳು',
      'fertilizer_pesticides': 'ರಸಗೊಬ್ಬರ ಮತ್ತು ಕೀಟನಾಶಕಗಳು',
      'borewell_services': 'ಬೋರ್‌ವೆಲ್ ಸೇವೆಗಳು',
      'irrigation_services': 'ನೀರಾವರಿ ಸೇವೆಗಳು',
      'transport_services': 'ಸಾರಿಗೆ ಸೇವೆಗಳು',
      'contract_farming': 'ಗುತ್ತಿಗೆ',
      
      // Service descriptions
      'soil_water_desc': 'ಆರೋಗ್ಯಕರ ಮಣ್ಣು ಮತ್ತು ನೀರನ್ನು ಖಚಿತಪಡಿಸಿ',
      'ploughing_desc': 'ಕ್ಷೇತ್ರ ತಯಾರಿಕೆ ಸುಲಭವಾಗಿದೆ',
      'cultivation_desc': 'ಸಂಪೂರ್ಣ ಬೆಳೆ ಕೃಷಿ',
      'fertilizer_desc': 'ಸುರಕ್ಷಿತವಾಗಿ ಬೆಳವಣಿಗೆಯನ್ನು ಹೆಚ್ಚಿಸಿ',
      'borewell_desc': 'ನೀರಿನ ಪರಿಹಾರಗಳು',
      'irrigation_desc': 'ವೃತ್ತಿಪರ ನೀರಾವರಿ',
      'transport_desc': 'ಸಾರಿಗೆ ಬೆಂಬಲ',
      'contract_desc': 'ಗುತ್ತಿಗೆ ಕೃಷಿ',
      
      // Booking
      'book_now': 'ಈಗ ಬುಕ್ ಮಾಡಿ',
      'booking_for': 'ಬುಕಿಂಗ್',
      'confirm_booking': 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ',
      'phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
      'address': 'ವಿಳಾಸ / ಸ್ಥಳ',
      'service_date': 'ಆದ್ಯತೆಯ ಸೇವಾ ದಿನಾಂಕ',
      'select_date': 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ',
      'booking_success': 'ಬುಕಿಂಗ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
      'payment_method': 'ಪಾವತಿ ವಿಧಾನ',
      'pay_now': 'ಈಗ ಪಾವತಿಸಿ',
      'upi_payment': 'UPI ಪಾವತಿ',
      'upi_id': 'UPI ID',
      'scan_qr': 'QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'payment_instructions': 'QR ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಥವಾ UPI ID ಬಳಸಿ ಪಾವತಿ ಮಾಡಿ',
      'booking_error': 'ಸೇವೆಯನ್ನು ಬುಕ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ',
      'fill_all_details': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಬುಕಿಂಗ್ ವಿವರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
      'invalid_phone': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ 10-ಅಂಕಿಯ ಫೋನ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      
      // Weather
      'weather_forecast': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
      'temperature': 'ತಾಪಮಾನ',
      'humidity': 'ಆರ್ದ್ರತೆ',
      'wind_speed': 'ಗಾಳಿಯ ವೇಗ',
      'rainfall': 'ಮಳೆ',
      
      // AI Crop Manager
      'ai_crop_manager': 'AI ಬೆಳೆ ವ್ಯವಸ್ಥಾಪಕ',
      'ask_question': 'ಬೆಳೆಗಳ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ...',
      'get_advice': 'AI ಸಲಹೆ ಪಡೆಯಿರಿ',
      
      // Footer
      'about_us_desc': 'ಅಗ್ರಿಕೇರ್ ಕೇವಲ ಕೆಲವು ಟ್ಯಾಪ್‌ಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಮನೆ ಬಾಗಿಲಿಗೆ ತಲುಪಿಸಲಾದ ವೃತ್ತಿಪರ ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ ಕೃಷಿ ಸೇವೆಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.',
      'quick_links': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
      'contact_us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'location': 'ಮಹಾಲಿಂಗಪುರ, ಕರ್ನಾಟಕ',
      'all_rights_reserved': 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
      
      // Common
      'close': 'ಮುಚ್ಚಿ',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'save': 'ಉಳಿಸಿ',
      'submit': 'ಸಲ್ಲಿಸಿ',
      'search': 'ಹುಡುಕಿ',
      'language': 'ಭಾಷೆ',
      'total': 'ಒಟ್ಟು',
      'pending': 'ಬಾಕಿ ಇದೆ',
      'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
      'price': 'ಬೆಲೆ',
      'status': 'ಸ್ಥಿತಿ',
      'no_bookings': 'ಇನ್ನೂ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ',
      'book_service': 'ಪ್ರಾರಂಭಿಸಲು ಸೇವೆಯನ್ನು ಬುಕ್ ಮಾಡಿ!',
      'close_form': 'ಫಾರ್ಮ್ ಮುಚ್ಚಿ',
      'view_details': 'ವಿವರಗಳನ್ನು ನೋಡಿ',
      
      // Subservices - Soil & Water Testing
      'basic_soil_test': 'ಮೂಲ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಪರೀಕ್ಷೆ',
      'npk_analysis': 'ಸಮಗ್ರ NPK ವಿಶ್ಲೇಷಣೆ',
      'water_salinity': 'ನೀರಿನ ಲವಣತೆ ಮತ್ತು pH ಪರೀಕ್ಷೆ',
      'heavy_metal': 'ಭಾರೀ ಲೋಹದ ಮಾಲಿನ್ಯ ಪರೀಕ್ಷೆ',
      'micronutrient': 'ಸೂಕ್ಷ್ಮ ಪೋಷಕಾಂಶ ವಿಶ್ಲೇಷಣೆ',
      
      // Subservices - Ploughing
      'tractor_ploughing': 'ಟ್ರಾಕ್ಟರ್ ಉಳುಮೆ (ಪ್ರತಿ ಎಕರೆ)',
      'deep_ploughing': 'ಆಳವಾದ ಉಳುಮೆ',
      'bullock_service': 'ಎತ್ತು ಸೇವೆ',
      'rotavator': 'ರೊಟಾವೇಟರ್ ಸೇವೆ',
      'harrow': 'ಹ್ಯಾರೋ ಸೇವೆ',
      'land_leveling': 'ಭೂಮಿ ಸಮತಟ್ಟಗೊಳಿಸುವಿಕೆ',
      
      // Subservices - Cultivation
      'seed_sowing': 'ಬೀಜ ಬಿತ್ತನೆ ಸೇವೆಗಳು',
      'transplanting': 'ನಾಟಿ ಮಾಡುವ ಸೇವೆಗಳು',
      'weeding': 'ಕಳೆ ಕಿತ್ತು ಮತ್ತು ಅಂತರ ಕೃಷಿ',
      'mulching': 'ಮಲ್ಚಿಂಗ್ ಸೇವೆಗಳು',
      'harvesting': 'ಬೆಳೆ ಕೊಯ್ಲು',
      
      // Subservices - Fertilizer
      'organic_fertilizer': 'ಸಾವಯವ ರಸಗೊಬ್ಬರ ಪೂರೈಕೆ',
      'npk_application': 'NPK ರಸಗೊಬ್ಬರ ಅನ್ವಯ',
      'pesticide_spray': 'ಕೀಟನಾಶಕ ಸಿಂಪಡಿಸುವಿಕೆ',
      'bio_pesticide': 'ಜೈವಿಕ ಕೀಟನಾಶಕ ಪರಿಹಾರಗಳು',
      'foliar_nutrition': 'ಎಲೆಗಳ ಪೋಷಣೆ ಸ್ಪ್ರೇ',
      
      // Subservices - Borewell
      'borewell_drilling': 'ಬೋರ್ವೆಲ್ ಕೊರೆಯುವಿಕೆ (200 ಅಡಿ ವರೆಗೆ)',
      'pump_installation': 'ಸಬ್ಮರ್ಸಿಬಲ್ ಪಂಪ್ ಸ್ಥಾಪನೆ',
      'borewell_cleaning': 'ಬೋರ್ವೆಲ್ ಸ್ವಚ್ಛಗೊಳಿಸುವಿಕೆ ಮತ್ತು ನಿರ್ವಹಣೆ',
      'water_testing': 'ನೀರಿನ ಇಳುವರಿ ಪರೀಕ್ಷೆ',
      'motor_repair': 'ಮೋಟಾರ್ ದುರಸ್ತಿ ಸೇವೆಗಳು',
      
      // Subservices - Irrigation
      'drip_irrigation': 'ಹನಿ ನೀರಾವರಿ ಸ್ಥಾಪನೆ',
      'sprinkler_system': 'ಸ್ಪ್ರಿಂಕ್ಲರ್ ವ್ಯವಸ್ಥೆ ಸ್ಥಾಪನೆ',
      'flood_irrigation': 'ಪ್ರವಾಹ ನೀರಾವರಿ ನಿರ್ವಹಣೆ',
      'irrigation_repair': 'ನೀರಾವರಿ ವ್ಯವಸ್ಥೆ ದುರಸ್ತಿ',
      'pipeline': 'ನೀರಿನ ಪೈಪ್‌ಲೈನ್ ಸ್ಥಾಪನೆ',
      
      // Subservices - Transport
      'farm_transport': 'ಕೃಷಿ ಉತ್ಪನ್ನ ಸಾರಿಗೆ',
      'livestock_transport': 'ಜಾನುವಾರು ಸಾರಿಗೆ',
      'equipment_transport': 'ಕೃಷಿ ಉಪಕರಣ ಸಾರಿಗೆ',
      'fertilizer_delivery': 'ರಸಗೊಬ್ಬರ ಮತ್ತು ಬೀಜ ವಿತರಣೆ',
      'cold_storage': 'ಶೀತ ಸಂಗ್ರಹ ಸಾರಿಗೆ',
      
      // Subservices - Contract
      'full_season': 'ಪೂರ್ಣ ಋತುವಿನ ಬೆಳೆ ನಿರ್ವಹಣೆ',
      'crop_contract': 'ಬೆಳೆ ಕೃಷಿ ಗುತ್ತಿಗೆ',
      'buyback': 'ಮರು-ಖರೀದಿ ಖಾತರಿ',
      'land_lease': 'ಭೂಮಿ ಗುತ್ತಿಗೆ ಒಪ್ಪಂದ',
      'custom_farming': 'ಕಸ್ಟಮ್ ಕೃಷಿ ಸೇವೆಗಳು',
      
      // Additional translations for pages
      'customer_reviews': 'ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು',
      'real_feedback': 'ಪರಿಶೀಲಿತ ಗ್ರಾಹಕರಿಂದ ನಿಜವಾದ ಪ್ರತಿಕ್ರಿಯೆ',
      'verified': 'ಪರಿಶೀಲಿತ',
      'helpful': 'ಸಹಾಯಕ',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'view_all_reviews': 'ಎಲ್ಲಾ ವಿಮರ್ಶೆಗಳನ್ನು ನೋಡಿ',
      'all_customer_reviews': 'ಎಲ್ಲಾ ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು',
      'reviews_average': 'ವಿಮರ್ಶೆಗಳು • {rating} ⭐ ಸರಾಸರಿ',
      'no_reviews_yet': 'ಇನ್ನೂ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ',
      'be_first_review': 'ವಿಮರ್ಶೆ ಬರೆಯುವ ಮೊದಲಿಗರಾಗಿ!',
      'leave_review': 'ವಿಮರ್ಶೆ ಬರೆಯಿರಿ',
      
      // Sample feedback data
      'sample_user_1': 'ರಮೇಶ್ ಕುಮಾರ್',
      'sample_user_2': 'ಸುನೀತಾ ದೇವಿ',
      'sample_service_1': 'ಟ್ರಾಕ್ಟರ್ ಉಳುವ ಸೇವೆ',
      'sample_service_2': 'NPK ಮಣ್ಣಿನ ಪರೀಕ್ಷೆ',
      'sample_comment_1': 'ಅತ್ಯುತ್ತಮ ಸೇವೆ! ಟ್ರಾಕ್ಟರ್ ಆಪರೇಟರ್ ಬಹಳ ವೃತ್ತಿಪರರಾಗಿದ್ದರು ಮತ್ತು ಸಮಯಕ್ಕೆ ಕೆಲಸ ಪೂರ್ಣಗೊಳಿಸಿದರು. ನನ್ನ ಹೊಲವನ್ನು ಸಂಪೂರ್ಣವಾಗಿ ಉಳಲಾಗಿದೆ. ಹೆಚ್ಚು ಶಿಫಾರಸು ಮಾಡುತ್ತೇನೆ!',
      'sample_comment_2': 'ಉತ್ತಮ ಸೇವೆ ಮತ್ತು ವಿವರವಾದ ಮಣ್ಣಿನ ವರದಿ. ಪರೀಕ್ಷೆಯು ನನ್ನ ಮಣ್ಣನ್ನು ಚೆನ್ನಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಲು ಸಹಾಯ ಮಾಡಿತು. ಸಾವಯವ ಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳನ್ನು ಒದಗಿಸುವುದು ಮಾತ್ರ ಸಲಹೆ.',
      'sample_date_1': '2 ದಿನಗಳ ಹಿಂದೆ',
      'sample_date_2': '1 ವಾರದ ಹಿಂದೆ',
      
      // Feedback service names
      'feedback_service_suggestion': 'ಸಲಹೆ',
      'feedback_service_bug': 'ಅಪ್ಲಿಕೇಶನ್ ಅನುಭವ',
      'feedback_service_compliment': 'ಸೇವಾ ಮೆಚ್ಚುಗೆ',
      'feedback_service_complaint': 'ಸೇವಾ ಸಮಸ್ಯೆ',
      'feedback_service_other': 'ಇತರ ಪ್ರತಿಕ್ರಿಯೆ',
      'feedback_service_general': 'ಸಾಮಾನ್ಯ ಸೇವೆ',
      'about_agricare': 'ಅಗ್ರಿಕೇರ್ ಬಗ್ಗೆ',
      'empowering_farmers': 'ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ರೈತರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು',
      'our_story': 'ನಮ್ಮ ಕಥೆ',
      'story_text': 'ಅಗ್ರಿಕೇರ್ ಅನ್ನು ಸರಳ ಉದ್ದೇಶದೊಂದಿಗೆ ಸ್ಥಾಪಿಸಲಾಗಿದೆ: ಗ್ರಾಮೀಣ ಭಾರತದ ಪ್ರತಿಯೊಬ್ಬ ರೈತನಿಗೆ ಕೃಷಿ ಸೇವೆಗಳನ್ನು ಪ್ರವೇಶಿಸುವಂತೆ ಮಾಡುವುದು. ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸಿಕೊಂಡು ರೈತರು ಮತ್ತು ನುರಿತ ಸೇವಾ ಪೂರೈಕೆದಾರರ ನಡುವಿನ ಅಂತರವನ್ನು ನಾವು ಕಡಿಮೆ ಮಾಡುತ್ತೇವೆ.',
      'farmers': 'ರೈತರು',
      'service_providers': 'ಸೇವಾ ಪೂರೈಕೆದಾರರು',
      'services_completed': 'ಪೂರ್ಣಗೊಂಡ ಸೇವೆಗಳು',
      'our_mission': 'ನಮ್ಮ ಧ್ಯೇಯ',
      'mission_text': 'ಕೈಗೆಟುಕುವ ಬೆಲೆಯಲ್ಲಿ ಗುಣಮಟ್ಟದ ಕೃಷಿ ಸೇವೆಗಳಿಗೆ ಸುಲಭ ಪ್ರವೇಶದೊಂದಿಗೆ ರೈತರನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು.',
      'our_vision': 'ನಮ್ಮ ದೃಷ್ಟಿ',
      'vision_text': 'ಭಾರತದಲ್ಲಿ ಕೃಷಿ ಸೇವೆಗಳಿಗಾಗಿ ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ ವೇದಿಕೆಯಾಗುವುದು.',
      'our_values': 'ನಮ್ಮ ಮೌಲ್ಯಗಳು',
      'trust': 'ವಿಶ್ವಾಸ',
      'trust_desc': 'ರೈತರೊಂದಿಗೆ ಶಾಶ್ವತ ಸಂಬಂಧಗಳನ್ನು ನಿರ್ಮಿಸುವುದು',
      'quality': 'ಗುಣಮಟ್ಟ',
      'quality_desc': 'ಅತ್ಯುತ್ತಮ ಸೇವಾ ಮಾನದಂಡಗಳನ್ನು ಖಚಿತಪಡಿಸುವುದು',
      'innovation': 'ನಾವೀನ್ಯತೆ',
      'innovation_desc': 'ಸಮಸ್ಯೆಗಳನ್ನು ಪರಿಹರಿಸಲು ತಂತ್ರಜ್ಞಾನವನ್ನು ಬಳಸುವುದು',
      'community': 'ಸಮುದಾಯ',
      'community_desc': 'ಗ್ರಾಮೀಣ ಅಭಿವೃದ್ಧಿಯನ್ನು ಬೆಂಬಲಿಸುವುದು',
      'contact_us': 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      'were_here_to_help': 'ನಿಮಗೆ ಸಹಾಯ ಮಾಡಲು ನಾವು ಇಲ್ಲಿದ್ದೇವೆ',
      'phone': 'ಫೋನ್',
      'whatsapp': 'ವಾಟ್ಸ್‌ಆಪ್',
      'address': 'ವಿಳಾಸ',
      'send_us_message': 'ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ',
      'your_name': 'ನಿಮ್ಮ ಹೆಸರು',
      'your_email': 'ನಿಮ್ಮ ಇಮೇಲ್',
      'your_phone': 'ನಿಮ್ಮ ಫೋನ್',
      'your_message': 'ನಿಮ್ಮ ಸಂದೇಶ',
      'send_message': 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      'office_locations': 'ಕಚೇರಿ ಸ್ಥಳಗಳು',
      'head_office': 'ಮುಖ್ಯ ಕಚೇರಿ',
      'regional_office': 'ಪ್ರಾದೇಶಿಕ ಕಚೇರಿ',
      'follow_us': 'ನಮ್ಮನ್ನು ಅನುಸರಿಸಿ',
      'we_value_feedback': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ ಮತ್ತು ಸಲಹೆಗಳನ್ನು ನಾವು ಗೌರವಿಸುತ್ತೇವೆ',
      'send_us_feedback': 'ನಮಗೆ ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಕಳುಹಿಸಿ',
      'rate_experience': 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ರೇಟ್ ಮಾಡಿ',
      'feedback_type': 'ಪ್ರತಿಕ್ರಿಯೆ ಪ್ರಕಾರ',
      'general_feedback': 'ಸಾಮಾನ್ಯ ಪ್ರತಿಕ್ರಿಯೆ',
      'bug_report': 'ದೋಷ ವರದಿ',
      'feature_request': 'ವೈಶಿಷ್ಟ್ಯ ವಿನಂತಿ',
      'complaint': 'ದೂರು',
      'compliment': 'ಪ್ರಶಂಸೆ',
      'your_feedback': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ',
      'tell_us_think': 'ನೀವು ಏನು ಯೋಚಿಸುತ್ತೀರಿ ಎಂದು ನಮಗೆ ತಿಳಿಸಿ...',
      'submit_feedback': 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ',
      'thank_you_feedback': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು!',
      'quick_feedback': 'ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ',
      'excellent_service': 'ಅತ್ಯುತ್ತಮ ಸೇವೆ!',
      'easy_to_use': 'ಬಳಸಲು ಸುಲಭ',
      'need_improvements': 'ಸುಧಾರಣೆಗಳ ಅಗತ್ಯವಿದೆ',
      'great_support': 'ಉತ್ತಮ ಬೆಂಬಲ',
      'more_features': 'ಹೆಚ್ಚಿನ ವೈಶಿಷ್ಟ್ಯಗಳು',
      'be_partner': 'ಪಾಲುದಾರರಾಗಿ',
      'join_network': 'ನಮ್ಮ ಕೃಷಿ ಸೇವಾ ಪೂರೈಕೆದಾರರ ಜಾಲಕ್ಕೆ ಸೇರಿ',
      'partner_benefits': 'ಪಾಲುದಾರ ಪ್ರಯೋಜನಗಳು',
      'more_customers': 'ಹೆಚ್ಚಿನ ಗ್ರಾಹಕರು',
      'flexible_work': 'ಹೊಂದಿಕೊಳ್ಳುವ ಕೆಲಸ',
      'fair_payments': 'ನ್ಯಾಯಯುತ ಪಾವತಿಗಳು',
      'training_support': 'ತರಬೇತಿ ಬೆಂಬಲ',
      'insurance_coverage': 'ವಿಮಾ ರಕ್ಷಣೆ',
      'how_it_works': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
      'apply_online': 'ಆನ್‌ಲೈನ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'fill_application': 'ನಮ್ಮ ಸರಳ ಅರ್ಜಿ ಫಾರ್ಮ್ ಅನ್ನು ಭರ್ತಿ ಮಾಡಿ',
      'verification': 'ಪರಿಶೀಲನೆ',
      'verify_skills': 'ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು ಮತ್ತು ದಾಖಲೆಗಳನ್ನು ನಾವು ಪರಿಶೀಲಿಸುತ್ತೇವೆ',
      'training': 'ತರಬೇತಿ',
      'free_training': 'ನಮ್ಮ ವೇದಿಕೆಯಲ್ಲಿ ಉಚಿತ ತರಬೇತಿ',
      'start_earning': 'ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
      'receive_requests': 'ಸೇವಾ ವಿನಂತಿಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
      'requirements': 'ಅವಶ್ಯಕತೆಗಳು',
      'experience_required': 'ಕೃಷಿ ಸೇವೆಗಳಲ್ಲಿ ಅನುಭವ',
      'valid_id': 'ಮಾನ್ಯ ID ಪುರಾವೆ ಮತ್ತು ವಿಳಾಸ ಪುರಾವೆ',
      'smartphone_knowledge': 'ಮೂಲಭೂತ ಸ್ಮಾರ್ಟ್‌ಫೋನ್ ಜ್ಞಾನ',
      'bank_account': 'ಪಾವತಿಗಳಿಗಾಗಿ ಬ್ಯಾಂಕ್ ಖಾತೆ',
      'serve_rural': 'ಗ್ರಾಮೀಣ ಪ್ರದೇಶಗಳಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸುವ ಇಚ್ಛೆ',
      'ready_to_join': 'ಸೇರಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
      'start_earning_today': 'ಇಂದೇ ಅಗ್ರಿಕೇರ್‌ನೊಂದಿಗೆ ಗಳಿಸಲು ಪ್ರಾರಂಭಿಸಿ',
      'apply_now': 'ಈಗ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'account': 'ಖಾತೆ',
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'alerts': 'ಎಚ್ಚರಿಕೆಗಳು',
      'profile_information': 'ಪ್ರೊಫೈಲ್ ಮಾಹಿತಿ',
      'update_personal_details': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವಿವರಗಳನ್ನು ನವೀಕರಿಸಿ',
      'privacy_security': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ',
      'manage_privacy_settings': 'ನಿಮ್ಮ ಗೌಪ್ಯತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'payment_methods': 'ಪಾವತಿ ವಿಧಾನಗಳು',
      'manage_payment_options': 'ನಿಮ್ಮ ಪಾವತಿ ಆಯ್ಕೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'enable_notifications': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
      'receive_app_notifications': 'ಅಪ್ಲಿಕೇಶನ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
      'email_notifications': 'ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು',
      'receive_updates_email': 'ಇಮೇಲ್ ಮೂಲಕ ನವೀಕರಣಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
      'sms_notifications': 'SMS ಅಧಿಸೂಚನೆಗಳು',
      'receive_sms_updates': 'SMS ನವೀಕರಣಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
      'push_notifications': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
      'receive_push_notifications': 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
      'app_preferences': 'ಅಪ್ಲಿಕೇಶನ್ ಆದ್ಯತೆಗಳು',
      'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'use_dark_theme': 'ಡಾರ್ಕ್ ಥೀಮ್ ಬಳಸಿ',
      'currency': 'ಕರೆನ್ಸಿ',
      'support_about': 'ಬೆಂಬಲ ಮತ್ತು ಬಗ್ಗೆ',
      'help_faq': 'ಸಹಾಯ ಮತ್ತು FAQ',
      'get_help_answers': 'ಸಹಾಯ ಪಡೆಯಿರಿ ಮತ್ತು ಉತ್ತರಗಳನ್ನು ಹುಡುಕಿ',
      'send_feedback': 'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ',
      'share_thoughts': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ನಮ್ಮೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ',
      'about_agricare': 'ಅಗ್ರಿಕೇರ್ ಬಗ್ಗೆ',
      'version': 'ಆವೃತ್ತಿ 2.0.1',
      'account_actions': 'ಖಾತೆ ಕ್ರಿಯೆಗಳು',
      'sign_out': 'ಸೈನ್ ಔಟ್',
      'sign_out_account': 'ನಿಮ್ಮ ಖಾತೆಯಿಂದ ಸೈನ್ ಔಟ್ ಮಾಡಿ',
      'delete_account': 'ಖಾತೆ ಅಳಿಸಿ',
      'permanently_delete': 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ',
      'coming_soon': 'ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ',
      'feature_development': 'ಈ ವೈಶಿಷ್ಟ್ಯವು ಅಭಿವೃದ್ಧಿಯಲ್ಲಿದೆ ಮತ್ತು ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಾಗುತ್ತದೆ.',
      'ok': 'ಸರಿ',
      'confirm_sign_out': 'ಸೈನ್ ಔಟ್ ದೃಢೀಕರಿಸಿ',
      'sure_sign_out': 'ನೀವು ಖಚಿತವಾಗಿ ಸೈನ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?',
      'cancel': 'ರದ್ದುಮಾಡಿ',
      'confirm_delete': 'ಖಾತೆ ಅಳಿಸುವಿಕೆಯನ್ನು ದೃಢೀಕರಿಸಿ',
      'sure_delete_account': 'ನೀವು ಖಚಿತವಾಗಿ ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಲು ಬಯಸುವಿರಾ? ಈ ಕ್ರಿಯೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.',
      'delete': 'ಅಳಿಸಿ',
      'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
      'english': 'English',
      'kannada': 'ಕನ್ನಡ (Kannada)',
      'hindi': 'हिंदी (Hindi)',
      'select_currency': 'ಕರೆನ್ಸಿ ಆಯ್ಕೆಮಾಡಿ',
      
      // Booking Form - Bill Calculator
      'area_acres': 'ಪ್ರದೇಶ (ಎಕರೆಗಳು)',
      'enter_area_acres': 'ಎಕರೆಗಳಲ್ಲಿ ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ',
      'area_required': 'ಪ್ರದೇಶ ಅಗತ್ಯವಿದೆ',
      'valid_area': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ',
      'bill_calculator': 'ಬಿಲ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'rate_per_acre': 'ಪ್ರತಿ ಎಕರೆಗೆ ದರ:',
      'enter_area_calculate': 'ಒಟ್ಟು ಮೊತ್ತವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಪ್ರದೇಶವನ್ನು ನಮೂದಿಸಿ',
      'total_amount': 'ಒಟ್ಟು ಮೊತ್ತ:',
      'number_of_persons': 'ವ್ಯಕ್ತಿಗಳ ಸಂಖ್ಯೆ',
      'enter_number_persons': 'ವ್ಯಕ್ತಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'persons_required': 'ವ್ಯಕ್ತಿಗಳ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ',
      'valid_persons': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ವ್ಯಕ್ತಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'number_of_days': 'ದಿನಗಳ ಸಂಖ್ಯೆ',
      'enter_number_days': 'ದಿನಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'days_required': 'ದಿನಗಳ ಸಂಖ್ಯೆ ಅಗತ್ಯವಿದೆ',
      'valid_days': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ದಿನಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'rate_per_person_day': 'ಪ್ರತಿ ವ್ಯಕ್ತಿ ಪ್ರತಿ ದಿನಕ್ಕೆ ದರ:',
      'persons_days': 'ವ್ಯಕ್ತಿಗಳು × ದಿನಗಳು:',
      'enter_persons_days_calculate': 'ಒಟ್ಟು ಮೊತ್ತವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ವ್ಯಕ್ತಿಗಳು ಮತ್ತು ದಿನಗಳನ್ನು ನಮೂದಿಸಿ',
      'select_fertilizer_product': 'ರಸಗೊಬ್ಬರ ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'choose_fertilizer': 'ರಸಗೊಬ್ಬರ ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'select_pesticide_product': 'ಕೀಟನಾಶಕ ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'choose_pesticide': 'ಕೀಟನಾಶಕ ಉತ್ಪನ್ನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'per_unit': 'ಪ್ರತಿ ಘಟಕ',
      'quantity_bags_packs': 'ಪ್ರಮಾಣ (ಚೀಲಗಳು/ಪ್ಯಾಕ್‌ಗಳು)',
      'quantity_bottles_packs': 'ಪ್ರಮಾಣ (ಬಾಟಲಿಗಳು/ಪ್ಯಾಕ್‌ಗಳು)',
      'enter_bags_packs': 'ಚೀಲಗಳು/ಪ್ಯಾಕ್‌ಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'enter_bottles_packs': 'ಬಾಟಲಿಗಳು/ಪ್ಯಾಕ್‌ಗಳ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
      'quantity_required': 'ಪ್ರಮಾಣ ಅಗತ್ಯವಿದೆ',
      'valid_quantity': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ಪ್ರಮಾಣವನ್ನು ನಮೂದಿಸಿ',
      'fertilizer_bill_calculator': 'ರಸಗೊಬ್ಬರ ಬಿಲ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'pesticide_bill_calculator': 'ಕೀಟನಾಶಕ ಬಿಲ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'selected_product': 'ಆಯ್ಕೆಮಾಡಿದ ಉತ್ಪನ್ನ:',
      'price_per_unit': 'ಪ್ರತಿ ಘಟಕದ ಬೆಲೆ:',
      'quantity_price': 'ಪ್ರಮಾಣ × ಬೆಲೆ:',
      'select_product_quantity': 'ಒಟ್ಟು ಮೊತ್ತವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಉತ್ಪನ್ನ ಮತ್ತು ಪ್ರಮಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'distance_kilometers': 'ದೂರ (ಕಿಲೋಮೀಟರ್‌ಗಳು)',
      'enter_distance_km': 'ಕಿಲೋಮೀಟರ್‌ಗಳಲ್ಲಿ ದೂರವನ್ನು ನಮೂದಿಸಿ',
      'distance_required': 'ದೂರ ಅಗತ್ಯವಿದೆ',
      'valid_distance': 'ದಯವಿಟ್ಟು ಮಾನ್ಯವಾದ ದೂರವನ್ನು ನಮೂದಿಸಿ',
      'transport_bill_calculator': 'ಸಾರಿಗೆ ಬಿಲ್ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'rate_per_kilometer': 'ಪ್ರತಿ ಕಿಲೋಮೀಟರ್‌ಗೆ ದರ:',
      'distance_rate': 'ದೂರ × ದರ:',
      'enter_distance_calculate': 'ಸಾರಿಗೆ ವೆಚ್ಚವನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ದೂರವನ್ನು ನಮೂದಿಸಿ',
    },
    
    'hi': {
      // App
      'app_title': 'एग्रीकेयर',
      'app_tagline': 'आधुनिक खेती में आपका साथी',
      'welcome': 'एग्रीकेयर में आपका स्वागत है',
      'hello': 'नमस्ते',
      'local_weather': 'स्थानीय मौसम पूर्वानुमान',
      'local_farm_area': 'स्थानीय कृषि क्षेत्र, भारत',
      'scattered_clouds': 'बिखरे बादल',
      'refresh_data': 'डेटा रिफ्रेश करें',
      'get_recommendations': 'सिफारिशें प्राप्त करें',
      'ai_crop_desc': 'अपनी भूमि के लिए सबसे लाभदायक फसलों के लिए AI-संचालित सिफारिशें प्राप्त करें।',
      'land_conditions_placeholder': 'यहां अपनी भूमि की स्थिति का वर्णन करें... जैसे, महाराष्ट्र में काली मिट्टी, बोरवेल से अच्छी पानी की उपलब्धता, गर्म जलवायु.',
      
      // Feedback
      'feedback': 'प्रतिक्रिया',
      'send_feedback': 'प्रतिक्रिया भेजें',
      'feedback_title': 'हम आपकी प्रतिक्रिया को महत्व देते हैं',
      'feedback_desc': 'अपने विचार, सुझाव या समस्याओं को साझा करके एग्रीकेयर को बेहतर बनाने में हमारी मदद करें।',
      'feedback_name': 'आपका नाम',
      'feedback_email': 'आपका ईमेल',
      'feedback_type': 'प्रतिक्रिया प्रकार',
      'feedback_message': 'आपका संदेश',
      'feedback_type_suggestion': 'सुझाव',
      'feedback_type_bug': 'बग रिपोर्ट',
      'feedback_type_compliment': 'तारीफ',
      'feedback_type_complaint': 'शिकायत',
      'feedback_type_other': 'अन्य',
      'feedback_placeholder': 'अपनी प्रतिक्रिया यहां साझा करें...',
      'feedback_success': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
      'feedback_error': 'प्रतिक्रिया भेजने में विफल। कृपया पुनः प्रयास करें।',
      
      // Why AgriCare section
      'why_agricare_title': 'क्यों एग्रीकेयर',
      'why_agricare_body': 'एग्रीकेयर किसानों को विश्वसनीय, तकनीक-सक्षम कृषि सेवाओं से जोड़ता है। ऑन-डिमांड ट्रैक्टर हायर से लेकर मिट्टी परीक्षण और फसल सलाह तक, हम आपको बेहतर निर्णय लेने और हर एकड़ से अधिक लाभ प्राप्त करने में मदद करते हैं।',
      'why_agricare_points': 'किसान हमें क्यों चुनते हैं:\n• प्रमाणित सेवा प्रदाता\n• पारदर्शी मूल्य निर्धारण\n• स्थानीय भाषा सहायता\n• बुकिंग से लेकर ट्रैकिंग तक पूरी सुविधा',
      'read_more': 'और जानें',
      
      // Local weather card
      'local_weather_card_title': 'स्थानीय मौसम',
      'local_weather_card_body': 'आज आपके खेत के क्षेत्र का तापमान, नमी और हवा की गति देखें।',
      'open': 'खोलें',
      
      // Auth
      'login': 'लॉगिन',
      'register': 'रजिस्टर',
      'email': 'ईमेल पता',
      'password': 'पासवर्ड',
      'name': 'पूरा नाम',
      'logout': 'लॉगआउट',
      'login_success': 'लॉगिन सफल!',
      'register_success': 'पंजीकरण सफल!',
      'logout_success': 'सफलतापूर्वक लॉगआउट हो गए',
      'farmer': 'किसान',
      'vendor': 'विक्रेता',
      'select_user_type': 'उपयोगकर्ता प्रकार चुनें',
      
      // Navigation
      'home': 'होम',
      'profile': 'प्रोफ़ाइल',
      'my_bookings': 'मेरी बुकिंग',
      'weather': 'मौसम पूर्वानुमान',
      'chat': 'सहायता चैट',
      'about_us': 'हमारे बारे में',
      'contact': 'संपर्क',
      'be_partner': 'साझेदार बनें',
      
      // Services
      'our_services': 'हमारी सेवाएं',
      'services_subtitle': 'आधुनिक खेती के लिए व्यापक कृषि समाधान',
      'soil_water_testing': 'मिट्टी और पानी परीक्षण',
      'ploughing_services': 'जुताई सेवाएं',
      'cultivation_services': 'खेती सेवाएं',
      'fertilizer_pesticides': 'उर्वरक और कीटनाशक',
      'borewell_services': 'बोरवेल सेवाएं',
      'irrigation_services': 'सिंचाई सेवाएं',
      'transport_services': 'परिवहन सेवाएं',
      'contract_farming': 'अनुबंध',
      
      // Service descriptions
      'soil_water_desc': 'स्वस्थ मिट्टी और पानी सुनिश्चित करें',
      'ploughing_desc': 'खेत की तैयारी आसान',
      'cultivation_desc': 'पूर्ण फसल खेती',
      'fertilizer_desc': 'सुरक्षित रूप से वृद्धि बढ़ाएं',
      'borewell_desc': 'पानी समाधान',
      'irrigation_desc': 'पेशेवर सिंचाई',
      'transport_desc': 'परिवहन सहायता',
      'contract_desc': 'अनुबंध खेती',
      
      // Booking
      'book_now': 'अभी बुक करें',
      'booking_for': 'बुकिंग',
      'confirm_booking': 'बुकिंग की पुष्टि करें',
      'phone_number': 'फोन नंबर',
      'address': 'पता / स्थान',
      'service_date': 'पसंदीदा सेवा तिथि',
      'select_date': 'तारीख चुनें',
      'booking_success': 'बुकिंग सफल!',
      'payment_method': 'भुगतान विधि',
      'pay_now': 'अभी भुगतान करें',
      'upi_payment': 'UPI भुगतान',
      'upi_id': 'UPI ID',
      'scan_qr': 'QR कोड स्कैन करें',
      'payment_instructions': 'QR कोड स्कैन करें या UPI ID का उपयोग करके भुगतान करें',
      'booking_error': 'सेवा बुक करने में विफल',
      'fill_all_details': 'कृपया सभी बुकिंग विवरण भरें',
      'invalid_phone': 'कृपया एक मान्य 10-अंकीय फोन नंबर दर्ज करें',
      
      // Weather
      'weather_forecast': 'मौसम पूर्वानुमान',
      'temperature': 'तापमान',
      'humidity': 'नमी',
      'wind_speed': 'हवा की गति',
      'rainfall': 'वर्षा',
      
      // AI Crop Manager
      'ai_crop_manager': 'AI फसल प्रबंधक',
      'ask_question': 'फसलों के बारे में प्रश्न पूछें...',
      'get_advice': 'AI सलाह प्राप्त करें',
      
      // Footer
      'about_us_desc': 'एग्रीकेयर कुछ ही टैप के साथ आपके दरवाजे तक पहुंचाई गई पेशेवर और विश्वसनीय कृषि सेवाएं प्रदान करता है।',
      'quick_links': 'त्वरित लिंक',
      'contact_us': 'संपर्क करें',
      'location': 'महालिंगपुर, कर्नाटक',
      'all_rights_reserved': 'सर्वाधिकार सुरक्षित',
      
      // Common
      'close': 'बंद करें',
      'cancel': 'रद्द करें',
      'save': 'सहेजें',
      'submit': 'जमा करें',
      'search': 'खोजें',
      'language': 'भाषा',
      'total': 'कुल',
      'pending': 'लंबित',
      'completed': 'पूर्ण',
      'price': 'मूल्य',
      'status': 'स्थिति',
      'no_bookings': 'अभी तक कोई बुकिंग नहीं',
      'book_service': 'शुरू करने के लिए एक सेवा बुक करें!',
      'close_form': 'फॉर्म बंद करें',
      'view_details': 'विवरण देखें',
      
      // Subservices - Soil & Water Testing
      'basic_soil_test': 'बुनियादी मिट्टी स्वास्थ्य परीक्षण',
      'npk_analysis': 'व्यापक NPK विश्लेषण',
      'water_salinity': 'पानी लवणता और pH परीक्षण',
      'heavy_metal': 'भारी धातु संदूषण परीक्षण',
      'micronutrient': 'सूक्ष्म पोषक तत्व विश्लेषण',
      
      // Subservices - Ploughing
      'tractor_ploughing': 'ट्रैक्टर जुताई (प्रति एकड़)',
      'deep_ploughing': 'गहरी जुताई',
      'bullock_service': 'बैल सेवा',
      'rotavator': 'रोटावेटर सेवा',
      'harrow': 'हैरो सेवा',
      'land_leveling': 'भूमि समतलीकरण',
      
      // Subservices - Cultivation
      'seed_sowing': 'बीज बोने की सेवाएं',
      'transplanting': 'रोपाई सेवाएं',
      'weeding': 'निराई और अंतर खेती',
      'mulching': 'मल्चिंग सेवाएं',
      'harvesting': 'फसल की कटाई',
      
      // Subservices - Fertilizer
      'organic_fertilizer': 'जैविक उर्वरक आपूर्ति',
      'npk_application': 'NPK उर्वरक अनुप्रयोग',
      'pesticide_spray': 'कीटनाशक छिड़काव',
      'bio_pesticide': 'जैव-कीटनाशक समाधान',
      'foliar_nutrition': 'पत्ते पोषण स्प्रे',
      
      // Subservices - Borewell
      'borewell_drilling': 'बोरवेल ड्रिलिंग (200 फीट तक)',
      'pump_installation': 'सबमर्सिबल पंप स्थापना',
      'borewell_cleaning': 'बोरवेल सफाई और रखरखाव',
      'water_testing': 'पानी उपज परीक्षण',
      'motor_repair': 'मोटर मरम्मत सेवाएं',
      
      // Subservices - Irrigation
      'drip_irrigation': 'ड्रिप सिंचाई स्थापना',
      'sprinkler_system': 'स्प्रिंकलर सिस्टम सेटअप',
      'flood_irrigation': 'बाढ़ सिंचाई प्रबंधन',
      'irrigation_repair': 'सिंचाई प्रणाली मरम्मत',
      'pipeline': 'पानी पाइपलाइन स्थापना',
      
      // Subservices - Transport
      'farm_transport': 'कृषि उत्पाद परिवहन',
      'livestock_transport': 'पशुधन परिवहन',
      'equipment_transport': 'कृषि उपकरण परिवहन',
      'fertilizer_delivery': 'उर्वरक और बीज वितरण',
      'cold_storage': 'कोल्ड स्टोरेज परिवहन',
      
      // Subservices - Contract
      'full_season': 'पूर्ण सीजन फसल प्रबंधन',
      'crop_contract': 'फसल खेती अनुबंध',
      'buyback': 'वापस खरीदारी गारंटी',
      'land_lease': 'भूमि पट्टा अनुबंध',
      'custom_farming': 'कस्टम खेती सेवाएं',
      
      // Additional translations for pages
      'customer_reviews': 'ग्राहक समीक्षाएं',
      'real_feedback': 'सत्यापित ग्राहकों से वास्तविक प्रतिक्रिया',
      'verified': 'सत्यापित',
      'helpful': 'सहायक',
      'yes': 'हाँ',
      'no': 'नहीं',
      'view_all_reviews': 'सभी समीक्षाएं देखें',
      'all_customer_reviews': 'सभी ग्राहक समीक्षाएं',
      'reviews_average': 'समीक्षाएं • {rating} ⭐ औसत',
      'no_reviews_yet': 'अभी तक कोई समीक्षा नहीं',
      'be_first_review': 'समीक्षा लिखने वाले पहले व्यक्ति बनें!',
      'leave_review': 'समीक्षा लिखें',
      
      // Sample feedback data
      'sample_user_1': 'रमेश कुमार',
      'sample_user_2': 'सुनीता देवी',
      'sample_service_1': 'ट्रैक्टर जुताई सेवा',
      'sample_service_2': 'NPK मिट्टी परीक्षण',
      'sample_comment_1': 'उत्कृष्ट सेवा! ट्रैक्टर ऑपरेटर बहुत पेशेवर था और समय पर काम पूरा किया। मेरा खेत पूरी तरह से जोता गया। अत्यधिक सिफारिश!',
      'sample_comment_2': 'अच्छी सेवा और विस्तृत मिट्टी रिपोर्ट। परीक्षण ने मुझे अपनी मिट्टी को बेहतर समझने में मदद की। केवल सुझाव जैविक उर्वरक सिफारिशें प्रदान करना है।',
      'sample_date_1': '2 दिन पहले',
      'sample_date_2': '1 सप्ताह पहले',
      
      // Feedback service names
      'feedback_service_suggestion': 'सुझाव',
      'feedback_service_bug': 'ऐप अनुभव',
      'feedback_service_compliment': 'सेवा प्रशंसा',
      'feedback_service_complaint': 'सेवा समस्या',
      'feedback_service_other': 'अन्य प्रतिक्रिया',
      'feedback_service_general': 'सामान्य सेवा',
      'about_agricare': 'एग्रीकेयर के बारे में',
      'empowering_farmers': 'तकनीक के साथ किसानों को सशक्त बनाना',
      'our_story': 'हमारी कहानी',
      'story_text': 'एग्रीकेयर की स्थापना एक सरल मिशन के साथ की गई थी: ग्रामीण भारत के हर किसान के लिए कृषि सेवाओं को सुलभ बनाना। हम तकनीक का उपयोग करके किसानों और कुशल सेवा प्रदाताओं के बीच की खाई को पाटते हैं।',
      'farmers': 'किसान',
      'service_providers': 'सेवा प्रदाता',
      'services_completed': 'पूर्ण सेवाएं',
      'our_mission': 'हमारा मिशन',
      'mission_text': 'किसानों को किफायती कीमतों पर गुणवत्तापूर्ण कृषि सेवाओं तक आसान पहुंच के साथ सशक्त बनाना।',
      'our_vision': 'हमारा विजन',
      'vision_text': 'भारत में कृषि सेवाओं के लिए सबसे विश्वसनीय प्लेटफॉर्म बनना।',
      'our_values': 'हमारे मूल्य',
      'trust': 'विश्वास',
      'trust_desc': 'किसानों के साथ स्थायी रिश्ते बनाना',
      'quality': 'गुणवत्ता',
      'quality_desc': 'सर्वोत्तम सेवा मानकों को सुनिश्चित करना',
      'innovation': 'नवाचार',
      'innovation_desc': 'समस्याओं को हल करने के लिए तकनीक का उपयोग',
      'community': 'समुदाय',
      'community_desc': 'ग्रामीण विकास का समर्थन',
      'contact_us': 'संपर्क करें',
      'were_here_to_help': 'हम आपकी मदद के लिए यहाँ हैं',
      'phone': 'फोन',
      'whatsapp': 'व्हाट्सएप',
      'address': 'पता',
      'send_us_message': 'हमें संदेश भेजें',
      'your_name': 'आपका नाम',
      'your_email': 'आपका ईमेल',
      'your_phone': 'आपका फोन',
      'your_message': 'आपका संदेश',
      'send_message': 'संदेश भेजें',
      'office_locations': 'कार्यालय स्थान',
      'head_office': 'मुख्य कार्यालय',
      'regional_office': 'क्षेत्रीय कार्यालय',
      'follow_us': 'हमें फॉलो करें',
      'we_value_feedback': 'हम आपकी प्रतिक्रिया और सुझावों को महत्व देते हैं',
      'send_us_feedback': 'हमें अपनी प्रतिक्रिया भेजें',
      'rate_experience': 'अपने अनुभव को रेट करें',
      'feedback_type': 'प्रतिक्रिया प्रकार',
      'general_feedback': 'सामान्य प्रतिक्रिया',
      'bug_report': 'बग रिपोर्ट',
      'feature_request': 'फीचर अनुरोध',
      'complaint': 'शिकायत',
      'compliment': 'तारीफ',
      'your_feedback': 'आपकी प्रतिक्रिया',
      'tell_us_think': 'हमें बताएं कि आप क्या सोचते हैं...',
      'submit_feedback': 'प्रतिक्रिया जमा करें',
      'thank_you_feedback': 'आपकी प्रतिक्रिया के लिए धन्यवाद!',
      'quick_feedback': 'त्वरित प्रतिक्रिया',
      'excellent_service': 'उत्कृष्ट सेवा!',
      'easy_to_use': 'उपयोग में आसान',
      'need_improvements': 'सुधार की आवश्यकता',
      'great_support': 'बेहतरीन सहायता',
      'more_features': 'अधिक सुविधाएं',
      'be_partner': 'साझेदार बनें',
      'join_network': 'हमारे कृषि सेवा प्रदाताओं के नेटवर्क में शामिल हों',
      'partner_benefits': 'साझेदार लाभ',
      'more_customers': 'अधिक ग्राहक',
      'flexible_work': 'लचीला काम',
      'fair_payments': 'निष्पक्ष भुगतान',
      'training_support': 'प्रशिक्षण सहायता',
      'insurance_coverage': 'बीमा कवरेज',
      'how_it_works': 'यह कैसे काम करता है',
      'apply_online': 'ऑनलाइन आवेदन करें',
      'fill_application': 'हमारा सरल आवेदन फॉर्म भरें',
      'verification': 'सत्यापन',
      'verify_skills': 'हम आपके कौशल और दस्तावेजों को सत्यापित करते हैं',
      'training': 'प्रशिक्षण',
      'free_training': 'हमारे प्लेटफॉर्म पर मुफ्त प्रशिक्षण',
      'start_earning': 'कमाना शुरू करें',
      'receive_requests': 'सेवा अनुरोध प्राप्त करना शुरू करें',
      'requirements': 'आवश्यकताएं',
      'experience_required': 'कृषि सेवाओं में अनुभव',
      'valid_id': 'वैध ID प्रमाण और पता प्रमाण',
      'smartphone_knowledge': 'बुनियादी स्मार्टफोन ज्ञान',
      'bank_account': 'भुगतान के लिए बैंक खाता',
      'serve_rural': 'ग्रामीण क्षेत्रों की सेवा करने की इच्छा',
      'ready_to_join': 'शामिल होने के लिए तैयार?',
      'start_earning_today': 'आज ही एग्रीकेयर के साथ कमाना शुरू करें',
      'apply_now': 'अभी आवेदन करें',
      'settings': 'सेटिंग्स',
      'account': 'खाता',
      'edit_profile': 'प्रोफाइल संपादित करें',
      'alerts': 'अलर्ट',
      'profile_information': 'प्रोफाइल जानकारी',
      'update_personal_details': 'अपनी व्यक्तिगत जानकारी अपडेट करें',
      'privacy_security': 'गोपनीयता और सुरक्षा',
      'manage_privacy_settings': 'अपनी गोपनीयता सेटिंग्स प्रबंधित करें',
      'payment_methods': 'भुगतान विधियां',
      'manage_payment_options': 'अपने भुगतान विकल्प प्रबंधित करें',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'receive_app_notifications': 'ऐप सूचनाएं प्राप्त करें',
      'email_notifications': 'ईमेल सूचनाएं',
      'receive_updates_email': 'ईमेल के माध्यम से अपडेट प्राप्त करें',
      'sms_notifications': 'SMS सूचनाएं',
      'receive_sms_updates': 'SMS अपडेट प्राप्त करें',
      'push_notifications': 'पुश सूचनाएं',
      'receive_push_notifications': 'पुश सूचनाएं प्राप्त करें',
      'app_preferences': 'ऐप प्राथमिकताएं',
      'dark_mode': 'डार्क मोड',
      'use_dark_theme': 'डार्क थीम का उपयोग करें',
      'currency': 'मुद्रा',
      'support_about': 'सहायता और जानकारी',
      'help_faq': 'सहायता और FAQ',
      'get_help_answers': 'सहायता प्राप्त करें और उत्तर खोजें',
      'send_feedback': 'फीडबैक भेजें',
      'share_thoughts': 'अपने विचार हमारे साथ साझा करें',
      'about_agricare': 'एग्रीकेयर के बारे में',
      'version': 'संस्करण 2.0.1',
      'account_actions': 'खाता क्रियाएं',
      'sign_out': 'साइन आउट',
      'sign_out_account': 'अपने खाते से साइन आउट करें',
      'delete_account': 'खाता हटाएं',
      'permanently_delete': 'अपना खाता स्थायी रूप से हटाएं',
      'coming_soon': 'जल्द आ रहा है',
      'feature_development': 'यह सुविधा विकास में है और जल्द ही उपलब्ध होगी।',
      'ok': 'ठीक है',
      'confirm_sign_out': 'साइन आउट की पुष्टि करें',
      'sure_sign_out': 'क्या आप वाकई साइन आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'confirm_delete': 'खाता हटाने की पुष्टि करें',
      'sure_delete_account': 'क्या आप वाकई अपना खाता स्थायी रूप से हटाना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',
      'delete': 'हटाएं',
      'select_language': 'भाषा चुनें',
      'english': 'English',
      'kannada': 'ಕನ್ನಡ (Kannada)',
      'hindi': 'हिंदी (Hindi)',
      'select_currency': 'मुद्रा चुनें',
      
      // Booking Form - Bill Calculator
      'area_acres': 'क्षेत्रफल (एकड़)',
      'enter_area_acres': 'एकड़ में क्षेत्रफल दर्ज करें',
      'area_required': 'क्षेत्रफल आवश्यक है',
      'valid_area': 'कृपया एक मान्य क्षेत्रफल दर्ज करें',
      'bill_calculator': 'बिल कैलकुलेटर',
      'rate_per_acre': 'प्रति एकड़ दर:',
      'enter_area_calculate': 'कुल राशि की गणना करने के लिए क्षेत्रफल दर्ज करें',
      'total_amount': 'कुल राशि:',
      'number_of_persons': 'व्यक्तियों की संख्या',
      'enter_number_persons': 'व्यक्तियों की संख्या दर्ज करें',
      'persons_required': 'व्यक्तियों की संख्या आवश्यक है',
      'valid_persons': 'कृपया व्यक्तियों की एक मान्य संख्या दर्ज करें',
      'number_of_days': 'दिनों की संख्या',
      'enter_number_days': 'दिनों की संख्या दर्ज करें',
      'days_required': 'दिनों की संख्या आवश्यक है',
      'valid_days': 'कृपया दिनों की एक मान्य संख्या दर्ज करें',
      'rate_per_person_day': 'प्रति व्यक्ति प्रति दिन दर:',
      'persons_days': 'व्यक्ति × दिन:',
      'enter_persons_days_calculate': 'कुल राशि की गणना करने के लिए व्यक्ति और दिन दर्ज करें',
      'select_fertilizer_product': 'उर्वरक उत्पाद चुनें',
      'choose_fertilizer': 'उर्वरक उत्पाद चुनें',
      'select_pesticide_product': 'कीटनाशक उत्पाद चुनें',
      'choose_pesticide': 'कीटनाशक उत्पाद चुनें',
      'per_unit': 'प्रति इकाई',
      'quantity_bags_packs': 'मात्रा (बैग/पैक)',
      'quantity_bottles_packs': 'मात्रा (बोतलें/पैक)',
      'enter_bags_packs': 'बैग/पैक की संख्या दर्ज करें',
      'enter_bottles_packs': 'बोतलों/पैक की संख्या दर्ज करें',
      'quantity_required': 'मात्रा आवश्यक है',
      'valid_quantity': 'कृपया एक मान्य मात्रा दर्ज करें',
      'fertilizer_bill_calculator': 'उर्वरक बिल कैलकुलेटर',
      'pesticide_bill_calculator': 'कीटनाशक बिल कैलकुलेटर',
      'selected_product': 'चयनित उत्पाद:',
      'price_per_unit': 'प्रति इकाई मूल्य:',
      'quantity_price': 'मात्रा × मूल्य:',
      'select_product_quantity': 'कुल राशि की गणना करने के लिए उत्पाद और मात्रा चुनें',
      'distance_kilometers': 'दूरी (किलोमीटर)',
      'enter_distance_km': 'किलोमीटर में दूरी दर्ज करें',
      'distance_required': 'दूरी आवश्यक है',
      'valid_distance': 'कृपया एक मान्य दूरी दर्ज करें',
      'transport_bill_calculator': 'परिवहन बिल कैलकुलेटर',
      'rate_per_kilometer': 'प्रति किलोमीटर दर:',
      'distance_rate': 'दूरी × दर:',
      'enter_distance_calculate': 'परिवहन लागत की गणना करने के लिए दूरी दर्ज करें',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  // Shorthand getter methods
  String get appTitle => translate('app_title');
  String get welcome => translate('welcome');
  String get login => translate('login');
  String get register => translate('register');
  String get email => translate('email');
  String get password => translate('password');
  String get ourServices => translate('our_services');
  String get bookNow => translate('book_now');
  String get myBookings => translate('my_bookings');
  String get language => translate('language');
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'kn', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
